Refactor podman-build shell script
- Added more comments explaining functionality.
- Wrapped repeated functionality in re-usable function.
- Added y/n validation for checking when application.jar was last time
modified, to make sure that the image will be based on the most recent
build.
- Improved usage function.
- Added validation to make sure that an existent image id is used.

diff --git a/scripts/podman-build b/scripts/podman-build
--- a/scripts/podman-build
+++ b/scripts/podman-build
@@ -1,11 +1,10 @@
 #!/bin/bash
 
-# Commands this script is executed with:
-# 1. `bash podman-build -i <environment_type>`. Environment type must be `dev` or `prod`
-# 2. `bash podman-build -c <image_id>. `image_id` is obtained beforehand with command `podman images`
-# 3. `bash podman-build -t <image_name_with_tag>
-# podman tag poliglotek:0.48.38-792b046 europe-west2-docker.pkg.dev/translation-to-polish-437813/poliglotek/poliglotek:0.48.38-792b046
-# podman push europe-west2-docker.pkg.dev/translation-to-polish-437813/poliglotek/poliglotek:0.48.38-792b046
+# Commands this script can be executed with:
+# 1. `bash podman-build -i <environment_type>`. Creates an image. Environment type must be `dev` or `prod`
+# 2. `bash podman-build -c <image_id>. Creates a container
+# 3. `bash podman-build -t <image_name_with_tag>. Tags an image before pushing to registry
+# 4. `bash podman-build -p <image_name_with_tag>. Pushes image to registry
 
 # Exit on error, undefined variable, or pipe failure
 set -euo pipefail
@@ -37,7 +36,6 @@ VALID_ENVIRONMENT_TYPES=("dev" "prod")
 G_CLOUD_REGION="europe-west2-docker.pkg.dev"
 G_CLOUD_PROJECT_ID="translation-to-polish-437813"
 
-
 check_dependencies() {
     for cmd in podman git; do
         command -v "$cmd" >/dev/null 2>&1 || { echo "Error: $cmd is not installed."; exit 1; }
@@ -61,30 +59,57 @@ get_git_branch_name() {
 # Image tag is retrieved using image id passed from the cli as an argument
 get_image_tag() {
     local image_id="$1" # To get image id use command `podman images` before running this script
-    podman images --filter "id=$image_id" --format "{{.Tag}}" || true
+    local image_tag
+    check_image_id_exists "$image_id"
+    image_tag=$(podman images --filter "id=$image_id" --format "{{.Tag}}" || true)
+    if [[ -z "$image_tag" ]]; then
+        echo "Error: Image with ID '$image_id' not found"
+        exit 1
+    fi
+    echo "$image_tag"
+}
+
+check_image_id_exists() {
+    local image_id="$1"
+    mapfile -t existing_image_ids < <(podman images --quiet)
+    if [[ ! " ${existing_image_ids[*]} " =~ ${image_id} ]]; then
+        echo "Error: Provided image id does not exist"
+        exit 1
+    fi
 }
 
 get_image_name_with_tag() {
     local image_id="$1"
-    podman images --filter "id=$image_id" --format "{{.Repository}}:{{.Tag}}"
+    local image_name_with_tag
+    check_image_id_exists "$image_id"
+    image_name_with_tag=$(podman images --filter "id=$image_id" --format "{{.Repository}}:{{.Tag}}" || true)
+    if [[ -z "$image_name_with_tag" ]]; then
+        echo "Error: Image with ID '$image_id' not found"
+        exit 1
+    fi
+    echo "$image_name_with_tag"
+}
+
+make_user_answer_case_insensitive() {
+    local user_answer="$1"
+    echo "$user_answer" | tr '[:upper:]' '[:lower]'
 }
 
 usage() {
-    echo "Usage: $0 <flag> <arg> [image_id]"
+    echo "Usage: $0 [OPTIONS] ARGUMENTS"
     echo
-    echo "Flags:"
-    echo "  -i, --image       Build a Podman image"
-    echo "  -c, --container   Run a Podman container"
-    echo "  -t, --tag         Tag image before pushing to registry"
-    echo "  -p, --push        Push image to registry"
-    echo
-    echo "Env:"
-    echo "  dev, prod         Mandatory environment specifier for image build"
+    echo "Options:"
+    echo "  -i, --image       Build a Podman image (requires environment: dev|prod)"
+    echo "  -c, --container   Run a Podman container (requires image ID)"
+    echo "  -t, --tag         Tag image before pushing to registry (requires image ID)"
+    echo "  -p, --push        Push image to registry (requires image ID)"
     echo
     echo "Examples:"
-    echo "  Build an image: $0 -i dev"
-    echo "  Run a container: $0 -c <image_id>"
-    echo "  Tag image before pushing it to registry: $0 -t <image_id>"
+    echo "  Build an image for development: $0 -i dev"
+    echo "  Run a container with image ID:  $0 -c <image_id>"
+    echo "  Tag an image:                   $0 -t <image_id>"
+    echo "  Push an image to the registry:  $0 -p <image_id>"
+    echo
     exit 1
 }
 
@@ -101,6 +126,25 @@ arg="$2"
 
 case $flag in
     -i|--image)
+    # Check if image is being created for the most recent build of the application
+    if [[ -e "$APP_JAR_FILE_PATH" ]]; then
+        last_modified=$(stat --format='%y' "$APP_JAR_FILE_PATH" | cut -c 1-16) # Drops seconds and millis
+        echo "The file was last modified on $last_modified"
+        echo "Make sure it's the most recent build"
+        read -r -t 30 -p "Do you want to continue creating image? (y/n?): " user_answer
+        user_answer=${user_answer:-n} # Defaults to `n` if not answered within 30 seconds
+        user_answer=$(make_user_answer_case_insensitive "$user_answer")
+        if [[ "${user_answer}" == "y" ]]; then
+            echo "Continuing..."
+        elif [[ "$user_answer" == "n" ]]; then
+            echo "Image not created. Exiting..."
+            exit 0
+        else
+            echo "Invalid input. Please answer 'y' or 'n'"
+            exit 0
+        fi
+    fi
+
     # Validate mandatory environment types for image build
     # Environment type is passed from the cli as an argument
     environment="${arg}"
@@ -127,12 +171,7 @@ case $flag in
     fi
     ;;
     -c|--container)
-    image_id="$arg"
-    image_tag=$(get_image_tag "$image_id")
-    if [[ -z "$image_tag" ]]; then
-        echo "Error: Image with ID '$image_id' not found"
-        exit 1
-    fi
+    image_tag=$(get_image_tag "$arg")
     container_name="${APP_NAME}-${image_tag}"
     echo "Running Podman container: $container_name"
 
@@ -146,12 +185,7 @@ case $flag in
     fi
     ;;
     -t|--tag)
-    image_id="$arg"
-    image_name_with_tag=$(get_image_name_with_tag "$image_id")
-    if [[ -z "$image_name_with_tag" ]]; then
-        echo "Error: Image with ID '$image_id' not found"
-        exit 1
-    fi
+    image_name_with_tag=$(get_image_name_with_tag "$arg")
     if podman tag "$image_name_with_tag" "$G_CLOUD_REGION"/"$G_CLOUD_PROJECT_ID"\
         /"${APP_NAME}"/"$image_name_with_tag"; then # APP_NAME is repo name in registry
         echo "Image $image_name_with_tag tagged for pushing to registry successfully"
@@ -161,12 +195,7 @@ case $flag in
     fi
     ;;
     -p|--push)
-    image_id="$arg"
-    image_name_with_tag=$(get_image_name_with_tag "$image_id")
-    if [[ -z "$image_name_with_tag" ]]; then
-            echo "Error: Image with ID '$image_id' not found"
-            exit 1
-    fi
+    image_name_with_tag=$(get_image_name_with_tag "$arg")
     if podman push "$G_CLOUD_REGION"/"$G_CLOUD_PROJECT_ID"/"${APP_NAME}"/"$image_name_with_tag"; then
         echo "Image $image_name_with_tag pushed to registry successfully "
     else
